transaction info screen done
IvanKhartanovich/modsen_banking pull request #4
Opened 2024-07-01 01:49 UTC by Arrttemka

transaction_info_screen

2024-07-01 07:10 UTC, IvanKhartanovich requested changes
Добавь какое-то подобие clean'а, как сейчас в develop. То есть тебе надо в папке features создать папку с названием своей фичи (transaction_info, допустим), там pages, widgets и entities раскидать по ним свои файлы

2024-07-01 07:10 UTC, IvanKhartanovich commented on lib/transaction_form.dart
> +        _buildReadOnlyField(transaction.amount),
_build-методы надо заменить виджетами Label и ReadOnlyField

2024-07-01 07:10 UTC, IvanKhartanovich commented on pubspec.yaml
> +  provider: ^6.0.0
Зачем?

2024-07-03 17:36 UTC, Arrttemka commented
изменил build'ы на Label, раскидал по папкам, файл styles запихнул в widgets, тк там прописаны стили для форм, думаю это уместно;) . добавил некоторые косметические изменения в ui

2024-07-03 17:53 UTC, merged